swagger: '2.0'

info:
  title: MyData - Notification API
  description: |
  
    This API specification describes MyData Notifications API. This document describes bot Operator and Service side endpoints. See [MyData Notifications]https://github.com/mydata-sdk/mydata-docs/tree/master/architecture_specs) for more details.
  version: '2.0'
  contact:
    url: 'https://github.com/mydata-sdk'
  license:
    name: 'MIT License (MIT)'
    url: 'https://opensource.org/licenses/MIT'




# host: 127.0.0.1:8080

schemes:
- https





produces:
  - application/json
consumes: 
- application/json

externalDocs:
  description: 'External documentation'
  url: 'https://github.com/mydata-sdk'
host: 127.0.0.1
paths:
  /notifications/{surrogate_id}/subscribtions/:
    post:
      summary: "Subscribes user to receive notifications"
      description: "Subscribes user identified by {surrogate_id} to receive notifications defined in payload. Actual subscription object is base64 encoded into body.payload and its structure is defined in Models section"
      tags: [Service]
      parameters:
        - name: surrogate_id
          in: path
          type: string
          description: 'user surrogate_id'
          required: true
        - name: subscription
          in: body
          description: 'JWS containing Subscription object'
          required: true
         
          schema:
            $ref: '#/definitions/JWSJsonSerializedFlattened'
      responses:
        '201':
          description: 'Subscription created'

        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error


  /notifications/{surrogate_id}:
    post:
      summary: "POST notification to user @operator"
      description: "Operator endpoint for POSTing notification to user identified by {surrogate_id}. Actual notification object is base64 encoded into body.payload and its structure is defined in Models section. Notifications MAY be encrypted using mechanisms defined in RFC7516, however this version of API specification does not define the data structures for encrypted notifications"
      tags: 
        [Operator]
      parameters:
        - name: surrogate_id
          in: path
          type: string
          description: 'user surrogate_id'
          required: true
        - name: subscription
          in: body
          description: 'JWS containing Subscription object'
          required: true
         
          schema:
            $ref: '#/definitions/JWSJsonSerializedFlattened'
      responses:
        '201':
          description: 'Notification received'

        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error


definitions:
  
  notification:
    type: object
    description: "object containing notificatins"
    properties:
      id:
        type: string
        description: "unique id"
      service_id: 
        type: string
        description: "ID of the service issueing this notification"
      sub:
        type: string
        description: "user surrogate_id"
      messages:
        type: array
        items:
          type: object
          properties:
            subject:
              type: string
              description: "notification subject"
            id:
              type: string
              description: "unique id"
            message:
              type: string
              description: "notification message"
            url:
              type: string
              description: "URL for additional information"

  subscription:
    type: object
    properties:
      id: 
        type: string
        description: "Unique ID"

      iat:
        type: string
        description: "When the request was issued"
      sub:
        type: string
        description: "Surrogate_id of the user"
      notifications:
        type: array
        items:
          type: string
          description: "id of the subscribed notification"
      encrypted:
        type: boolean
        description: "whether user requests notifications to be encryted or not"
  JWSJsonSerializedFlattened:
    type: object
    properties:
      header:
        type: object
        properties:
          kid:
            type: string
      payload:
        type: string
      protected:
        type: string
      signature:
        type: string