swagger: '2.0'
info:
  title: MyData - Service Registry Search API
  description: |
    This API specification describes MyData Service Registry API and defines endpoints for registering and searching registered services from the Service Registry. See [MyData Service Description]([MyData Specifications](https://github.com/mydata-sdk/mydata-docs/tree/master/architecture_specs) for more details on Service Descriptions.
  version: '2.0'
  contact:
    url: 'https://github.com/mydata-sdk'
  license:
    name: 'MIT License (MIT)'
    url: 'https://opensource.org/licenses/MIT'
host: 127.0.0.1

schemes:
 - https
consumes:
  - application/json

produces:
  - application/json


paths:
  /api/v1/services/:
    get:
      summary: "Returns all service descriptions"
      description: "Returns all source or sink services where serviceType={service_type} if present in query parameter or all service descriptions if query parameter missing. Response objects can contain both serviceDescription_source or serviceDescription_sink types. See Models section for more details"
      parameters:
        - name: serviceType
          in: query
          type: string
          enum: [source, sink]
          description: 'service type source or sink'
          required: false

      responses:
        '200':
          description: 'List of all registerd service descriptions with serviceType={service_type} if present in query string, otherwise all services'

          schema:
             $ref: '#/definitions/serviceDescriptions'
       



        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error

  
    post:
      summary: "Saves service description"
      description: "Saves service description to database. Body can be of type serviceDescription_source or serviceDescription_sink. See Models section for more details."


      parameters:

        - name: serviceDescription
          in: body
          description: 'Service description'
          required: true
         
          schema:
            $ref: '#/definitions/serviceDescription_source'
      

      responses:
        '201':
          description: 'Service description saved to db'
          headers:
            Location:
              type: string
              description: location of the created object
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error
  
          

  /api/v1/services/search/:
    get:
      summary: "Returns all service descriptions containing {searchTerm}"
      description: "Returns all service descriptions containing {searchTerm}, limits to {service_type} type service if defined in serviceType={service_type} query parameter. Response objects can contain both serviceDescription_source or serviceDescription_sink types. See Models section for more details"
      parameters:
        - name: serviceType
          in: query
          type: string
          enum: [source, sink]
          description: 'service type source or sink'
          required: false
        - name: serchTerm
          in: query
          type: string
          description: 'string to search'
          required: true

      responses:
        '200':
          description: 'List of registerd service descriptions matching with {searchTerm}, limited to services with serviceType={service_type} if present in query string, otherwise all matching services'

          schema:
             $ref: '#/definitions/serviceDescriptions'
       



        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error



  /api/v1/services/{service_id}/:
    get:
      summary: "Returns service description for service {service_id}"
      description: "Returns service description with id {service_id}. Response object can be either type serviceDescription_source or serviceDescription_sink. See Models section for more details."
      parameters:
        - name: service_id
          in: path
          type: string
          description: 'Service Id'
          required: true
      responses:
        '200':
          description: 'Service description for service {service_id}'
          schema:
             $ref: '#/definitions/serviceDescription_source'
       



        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error
  
  /api/v1/services/{service_id}/compatible:
    get:
      summary: "Returns array of services compatible with service {id}"
      description: "Returns array of service descriptions compatible with serviceId = {service_id}, if serviceType={servicetype} query parameter is present limits to source or sink services. Service description objects can be either type serviceDescription_source or serviceDescription_sink. See Models section for more details."
      parameters:
        - name: service_id
          in: path
          type: string
          description: 'Service Id'
          required: true
        - name: serviceType
          in: query
          type: string
          enum: [source, sink]
          description: 'service type source or sink'
          required: false
          
      responses:
        '200':
          description: 'Array of service descriptions compatible with service with serviceId={service_id}'
          schema:
             $ref: '#/definitions/serviceDescriptions'
       



        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '500':
          description: Internal Server error
    

definitions:


  serviceDescriptions:
    type: array
    items:
      $ref: '#/definitions/serviceDescription_source'
        
  serviceDescription_source:
    type: object
    properties:
      serviceId: 
        type: string
      serviceDescription:
        type: object
        properties:
          serviceProvider:
            type: object
            properties:
              id: 
                type: string
              businessID: 
                type: string
              name: 
                type: string
              address1: 
                type: string
              address2: 
                type: string
              postalCode: 
                type: string
              city: 
                type: string
              state: 
                type: string
              country: 
                type: string
              contactEmail: 
                type: string
              contactTel: 
                type: string
              jurisdiction: 
                type: string
          serviceDescriptionVersion: 
            type: string
          serviceDescriptionTitle: 
            type: string
          serviceIconURL: 
            type: string
          serviceType: 
            type: string
            enum: ["source"]
          cert:
            type: object
            properties:
              x5u: 
                type: string
          serviceUrls:
            type: object
            properties:
              domain: 
                type: string
              libraryDomain: 
                type: string
              linkingUri: 
                type: string
              linkingRedirectUri: 
                type: string
          compatibleServices:
            type: array
            items:
              type: string
          description:
            type: array
            items:
              type: object
              properties:
                language:
                  type: string
                humanReadableDescription:
                  type: string
                keywords:
                  type: array
                  items:
                    type: string
      dataDescription:
        type: array
        items:
          type: object
          properties:
            datasetId: 
              type: string
            description: 
              type: array
              items:
                type: object
                properties:
                  title: 
                    type: string
                  language:
                    type: string
                  description:
                    type: string
                  keywords:
                    type: array
                    items:
                      type: string

            datasetSchema:
              type: object
              properties:
                "@context":
                  type: string
                "@type": 
                  type: string 
                "@id": 
                  type: string
                url: 
                  type: string
            distribution:
              type: array
              items:
                type: object
                properties:
                  distributionId:
                    type: string
                  accessURL:
                    type: string
                  format: 
                    type: string

      createdOnDate: 
        type: string
      createdByUserId:
        type: string
 
  serviceDescription_sink:
    type: object
    properties:
      serviceId: 
        type: string
      serviceDescription:
        type: object
        properties:
          serviceProvider:
            type: object
            properties:
              id: 
                type: string
              businessID: 
                type: string
              name: 
                type: string
              address1: 
                type: string
              address2: 
                type: string
              postalCode: 
                type: string
              city: 
                type: string
              state: 
                type: string
              country: 
                type: string
              contactEmail: 
                type: string
              contactTel: 
                type: string
              jurisdiction: 
                type: string
          serviceDescriptionVersion: 
            type: string
          serviceDescriptionTitle: 
            type: string
          serviceIconURL: 
            type: string
          serviceType: 
            type: string
            enum: [sink]
          cert:
            type: object
            properties:
              x5u: 
                type: string
          serviceUrls:
            type: object
            properties:
              domain: 
                type: string
              libraryDomain: 
                type: string
              linkingUri: 
                type: string
              linkingRedirectUri: 
                type: string
          compatibleServices:
            type: array
            items:
              type: string
          description:
            type: array
            items:
              type: object
              properties:
                language:
                  type: string
                humanReadableDescription:
                  type: string
                keywords:
                  type: array
                  items:
                    type: string
      processing_bases:
        type: object
        properties:
          contract:
            type: array
            items:
              $ref: '#/definitions/processingBase'
          consent:
            type: array
            items:
              $ref: '#/definitions/processingBase'
          publicInterest:
            type: array
            items:
              $ref: '#/definitions/processingBase'
          legitimateInterest:
            type: array
            items:
              $ref: '#/definitions/processingBase'
          vitalInterest:
            type: array
            items:
              $ref: '#/definitions/processingBase'
      createdOnDate: 
        type: string
      createdByUserId:
        type: string
  
  processingBase:
    type: object
    properties:
      purposeId:
        type: string
      description:
        type: array
        items:
          type: object
          properties:
            language:
              type: string
            descriptionUrl:
              type: string
            title:
              type: string
            description:
              type: string
            iconUrl:
              type: string
      requiredDatasets:
        type: array
        items: 
          type: string
      optionaldDatasets:
        type: array
        items: 
          type: string                        