swagger: '2.0'
info:
  title: 'MyData Operator API for Source services'
  description: |
    This API specification describes MyData Operator API that is used by MyData compliant source services. For complementary Operator - service API specification see [MyData Service API for Operator](https://github.com/mydata-sdk/mydata-docs/tree/master/api_specs). For detailed description   see [MyData documenttation](https://github.com/mydata-sdk/mydata-docs/tree/master/architecture_specs).
  version: '2.0'
  contact:
    url: 'https://github.com/mydata-sdk'
  license:
    name: 'MIT License (MIT)'
    url: 'https://opensource.org/licenses/MIT'
externalDocs:
  description: 'External documentation'
  url: 'https://github.com/mydata-sdk'
host: 12.0.0.1
schemes:
 - https
paths:

  /link:
    post:
      tags:
      - "Service Linking"
      description: "End point where Service Management POSTs after user has been authenticated\
        \ by the Service and has accepted service linking in order to deliver surrogate id to Operator. This endpoint is part of the Service Linking flow and should not be called independently. For detailed description of Service Linking flow see [MyData Service Linking](https://github.com/mydata-sdk/mydata-docs/tree/master/architecture_specs)"
      summary: "Inform Operator we're ready to continue creation of Service Link Record"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Contains code, surrogate_id and in case of Sink service a token_key"
        required: true
        schema:
          $ref: "#/definitions/LinkParams"
      responses:
        201:
          description: "Returns 201 CREATED and the created Service Link Record"
          schema:
            $ref: "#/definitions/VerifyResponse"
        500:
          description: "Internal server error"
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /verify:
    post:
      tags:
      - "Service Linking"
      description: "End point where Service Management POSTs after signing Service Link Record received from Operator. This endpoint is part of the Service Linking flow and should not be called independently. For detailed description   see [MyData Service Linking](https://github.com/mydata-sdk/mydata-docs/tree/master/architecture_specs)"
      summary: "Send Service Signed Service Link Record back to Operator for verification"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "slr and ssr"
        required: true
        schema:
          $ref: "#/definitions/VerifyParams"
      responses:
        201:
          description: "Returns 201 CREATED so Service Mngmt knows SLR was verified\
            \ successfully"
          schema:
            $ref: "#/definitions/VerifyResponse"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"
            

  /introspection/{cr_id}:
    get:
      tags:
      - "Consent Management"
      description: "Gets latest consent status record's id for given consent record id"
      summary: "Get last consent status record id"
      parameters:
      - name: "cr_id"
        in: "path"
        description: "Unique ID of consent record"
        required: true
        type: "string"

      responses:
        200:
          description: "returns 200 OK and latest consent status record id"
          schema:
            $ref: "#/definitions/IntrospectionReply"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"

  /consent/{cr_id}/missing_since/{csr_id}:
    get:
      tags:
      - "Consent Management"
      description: "Gets new consent status records for given consent record since given consent status record id"
      summary: "Get missing consent status records"
      parameters:
      - name: "cr_id"
        in: "path"
        description: "Unique ID of consent record"
        required: true
        type: "string"
      - name: "csr_id"
        in: "path"
        description: "Unique ID of consent status record"
        required: true
        type: "string"
      responses:
        200:
          description: "returns 200 OK and new consent status records since given consent status record id"
          schema:
            $ref: "#/definitions/IntrospectionMissingReply"
        500:
          description: "Internal server error. The actual status code and content of the error message may vary depending on error occurred."
          schema:
            $ref: "#/definitions/errors"
        502:
          description: "Bad Gateway"
          schema:
            $ref: "#/definitions/errors"
            
        
            
definitions:
  errors:
      type: object
      properties:
        status:
          type: string
          description: HTTP status code as string value.
        code:
          type: integer
          description: HTTP status code
        title:
          type: string
          description: Title of error message.
        detail:
          type: string
          description: Detailed error message.
        source:
          type: string
          description: Source URI


  IntrospectionReply:
    type: object
    properties:
      csr_id:
        type: string
        description: string containing csr_id

  IntrospectionMissingReply:
    type: object
    properties:
      missing_csr:
        type: object
        properties:
          data:
            type: array
            items:
              type: object
              properties:
                attributes:
                  type: object
                  description: Missing csr
    
  SLR_raw:
    type: "object"
    properties:
      protected:
        type: "string"
      payload:
        type: "string"
      signatures:
        type: array
        items:
          type: object

  SLR_content:
   type: "object"
   properties:
    attributes:
      $ref: '#/definitions/SLR_raw'
    type:
      type: "string"
    id:
      type: "string"

  SSR_content:
   type: "object"
   properties:
    attributes:
      type: "object"
      properties:
        header:
          type: "object"
        protected:
          type: "string"
        payload:
          type: "string"
        signature:
          type: "string"
    type:
      type: "string"
    id:
      type: "string"


  LinkParams:
    type: "object"
    properties:
      code:
        type: "string"
        description: "string containing code"
      token_key:
        $ref: "#/definitions/LinkParams_token_key"
      surrogate_id:
        type: "string"
        description: "string containing surrogate_id"

  VerifyParams:
    type: "object"
    properties:
      data:
        type: object
        properties:
          code:
            type: string
            description: string containing code
      slr:
        $ref: "#/definitions/SLR_raw"

  LinkParams_token_key:
    type: "object"
    properties:
      kty:
        type: "string"
        description: "string containing kty"
      x:
        type: "string"
        description: "string containing x"
      kid:
        type: "string"
        description: "string containing kid"
      crv:
        type: "string"
        description: "string containing crv"
      y:
        type: "string"
        description: "string containing y"

  VerifyResponse:
    type: object
    properties:
      code:
        type: string
        description: string containing code
      data:
        type: object
        properties:
          ssr:
            $ref: "#/definitions/SSR_content"
          slr:
            $ref: "#/definitions/SLR_content"


            
